name: widgets
description: A new Flutter project named widgets.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  http: ^1.3.0
  email_otp_auth: ^1.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  flutter_dotenv: ^6.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/bever.png
    - assets/icons/animal.png
    - assets/icons/deer.png
    - assets/icons/agriculture.png
  # - assets/loaders/loading_paw.json
    - .env
